### ISSUE TITLE
Problem on form

### ISSUE THREAD

**Issue by bishal1919** [purnima-poo/tax#1]
On index.html there are many form. There should be only one form.

**Comment by purnima-gosain** [comment]
That code should be handled by frontend as index.html code includes frontend works. Please assign to frontend developer.

**Comment by bishal1919** [comment]
Ok. I'll do that.

**Comment by NymphetamineHunter** [comment]
I reviewed the Backend code. Try removing the multiple form tags. I suggest using the following code <form class='"income" method="POST"> instead.

**Comment by purnima-gosain** [comment]
This issue is nicely fixed. :)
